// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function string(v) {
  return v;
}

function number(v) {
  return v;
}

var Json_info_limit = {
  string: string,
  number: number
};

function string$1(v) {
  return v;
}

function number$1(v) {
  return v;
}

var Text_info_limit = {
  string: string$1,
  number: number$1
};

function string$2(v) {
  return v;
}

function number$2(v) {
  return v;
}

var Buffer_info_limit = {
  string: string$2,
  number: number$2
};

exports.Json_info_limit = Json_info_limit;
exports.Text_info_limit = Text_info_limit;
exports.Buffer_info_limit = Buffer_info_limit;
/* No side effect */
