// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var OpensslSelfSignedCertificate = require("openssl-self-signed-certificate");

var key = OpensslSelfSignedCertificate.key;

var cert = OpensslSelfSignedCertificate.cert;

var passphrase = OpensslSelfSignedCertificate.passphrase;

var options = {
  key: key,
  cert: cert,
  passphrase: passphrase
};

function func(prim, prim$1, prim$2, prim$3) {
  return prim.getData(prim$1, prim$2, prim$3);
}

var nameOfTestObjekt = func(OpensslSelfSignedCertificate, "Herr", 54, "444");

console.log("nameOfTestObjekt:", nameOfTestObjekt);

exports.key = key;
exports.cert = cert;
exports.passphrase = passphrase;
exports.options = options;
exports.nameOfTestObjekt = nameOfTestObjekt;
/* key Not a pure module */
