// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Micro = require("micro");

var server = Micro((function (req, res) {
        return "Hello, world!";
      }));

server.listen(1337);

exports.server = server;
/* server Not a pure module */
