// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Micro = require("micro");

function add(a, b) {
  return a + b | 0;
}

var server = Micro(function (req, res) {
      return "Hello, World " + String(500);
    });

console.log("http://localhost:" + 1337 + "/");

server.listen(1337);

var port = 1337;

exports.port = port;
exports.add = add;
exports.server = server;
/* server Not a pure module */
